### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by lizllanos** [CIAT-DAPA/usaid_hnd#6]
- [x] Realizar qc y llenado para datos de enee de precipitación

- [x] Procesar datos de temperaturas de ENEE

- [x] Realizar llenado de datos para temperaturas, evaluar fuente A-Where
